DEFAULT_MODEL_PATH = "./Qwen2.5-1.5B-Instruct"
DEFAULT_DOPT_CONFIG = "dopt_conf/qwen2.5-1.5b.json"
DEFAULT_OPTIMIZE_CONFIG = "optimize-config.yaml"
DEFAULT_OUTPUT_DIR = "dopt_out"
DEFAULT_GROUP_SIZE = 128
DEFAULT_BLOCK_SIZE = 128
DEFAULT_ACT_BITS = 16
DEFAULT_W_BITS = 4